#!/usr/bin/sh
set -e
#
# The Qubes OS Project, https://www.qubes-os.org#
#
# Copyright (C) 2019 Martin Holst Swende <martin@swende.se>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#

# This file should be placed in  /usr/bin/qvm-sync
#
# Or maybe /usr/local/ should be used, for persistence
# across restarts

BINDIR=/usr/lib/qubes
PROGRAM_NAME=${0##*/}

OPERATION_TYPE="copy"
TARGET_TYPE="default"


if [ "$1" = "--without-progress" ] ; then
	export PROGRESS_TYPE=none
	shift
else
	export PROGRESS_TYPE=console
fi

echo "/usr/lib/qubes/qrexec-client-vm "@default" qubes.Filesync $BINDIR/qsync-send \"$@\""

/usr/lib/qubes/qrexec-client-vm "@default" qubes.Filesync $BINDIR/qsync-send "$@"